### ISSUE TITLE
拖入upload组件报错

### ISSUE THREAD

**Issue by taojunnan** [sscfaith/avue-form-design#12]
Element-ui: 2.13.2
Avue: 2.6

![image](https://user-images.githubusercontent.com/18263998/83970390-17a8ea80-a908-11ea-9f88-84f2bb8b8096.png)
![image](https://user-images.githubusercontent.com/18263998/83970405-268f9d00-a908-11ea-94e2-e20eb39fd2e1.png)

拖入后默认的JSON，header和data为Array，但是Element Upload组件这两个参数接收的是Object类型
``` json
{
  "column": [
    {
      "type": "upload",
      "label": "上传",
      "span": 24,
      "display": true,
      "showFileList": true,
      "multiple": true,
      "limit": 10,
      "props": {},
      "propsHttp": {},
      "canvasOption": {},
      "headers": [],
      "data": [],
      "size": "small",
      "prop": "1591537647008_34642"
    }
  ]
}
```

**Comment by sscfaith** [comment]
感谢，最新版已修复

**Comment by taojunnan** [comment]
@sscfaith 其他组件好像也有类似的问题你试一下

**Comment by sscfaith** [comment]
@taojunnan 好
