### ISSUE TITLE
添加事件属性

### ISSUE THREAD

**Issue by wangyixiang-556** [sscfaith/avue-form-design#23]
保存 json 时 value 值保存为字符串，通过 eval 或者 new Function( ) 执行函数，这个思路能行吗?

**Comment by sscfaith** [comment]
最新版已经有事件属性了，展示没法展示，复制按钮可以

**Comment by wangyixiang-556** [comment]
最新版那个预览的时候会直接执行，能通过改源码在组件上添加一个id吗？然后通过new Function动态添加监听事件？用bind把this整上去，像这样：
<input type="text" placeholder="val" v-model="val" />
<div id="test">
  <input type="text" placeholder="test" v-model="test">
  <button @click="add">添加</button>
</div>
add() {
  let fun = new Function('return ' + this.val)
  document.getElementById('test').childNodes[0].addEventListener('change',fun.bind(this),false)
},
