### ISSUE TITLE
如何自定义左侧配置项

### ISSUE THREAD

**Issue by xiaohe2510** [sscfaith/avue-form-design#28]
我需要的左侧只有基础的一些表单配置，我想隐藏不用的表单配置，能够支持配置这个兼容吗，我自己更改了源码不知到如何添加

**Comment by sscfaith** [comment]
[最新版已支持](https://github.com/sscfaith/avue-form-design/blob/master/CHANGELOG.md)

**Comment by xiaohe2510** [comment]
集成 生成JSON报错
![image](https://user-images.githubusercontent.com/50822101/93876699-d77c4500-fd09-11ea-888f-a591b08b4655.png)
