### ISSUE TITLE
子组件数据未响应式

### ISSUE THREAD

**Issue by yeyuguo** [sscfaith/avue-form-design#31]
子数据未响应式  😭

**Comment by yeyuguo** [comment]
生成json，编辑属性第二次之后，不会再生效

**Comment by yeyuguo** [comment]
点击生成json - 关闭弹窗- 编辑 config 属性 - 再次点击“生成json” 不响应式，因为数据是直接更改了 props

**Comment by yeyuguo** [comment]
你们的 vue-devtool 有正常出现吗？

**Comment by sscfaith** [comment]
请更新最新版
