### ISSUE TITLE
默认生成导出json为js，希望支持可选string类型，如：https://form.avuejs.com/?type=string

### ISSUE THREAD

**Issue by hhr66** [sscfaith/avue-form-design#33]

**Comment by sscfaith** [comment]
https://github.com/sscfaith/avue-form-design/blob/master/CHANGELOG.md#2020-10-29
可以使用getData('string')方法

**Comment by hhr66** [comment]
使用需求场景是工单系统生成form表单是要提交到后端保存数据库里，js格式json解析不了

**Comment by hhr66** [comment]
getData('string')这需要自己去部署吧？想直接跳转到你们官方提供的地址生成json

**Comment by sscfaith** [comment]
https://form.beta.kim/

**Comment by sscfaith** [comment]
https://form.beta.kim/
看这是否符合你的需求

**Comment by hhr66** [comment]
不行，复制出来的还是js格式，需要key带引号，如{"key": "value"}

**Comment by sscfaith** [comment]
再看下

**Comment by hhr66** [comment]
复制那弹出的配置窗口类型选项没作用吧， 通过设置移除key的引号和引号类型能到达获得string类型的数据了。能使用，但使用体验有些不友好

**Comment by hhr66** [comment]
看复制弹窗的配置项也没几个，建议把这些配置参数放在url里面，可以可根据自己的使用场景去设置，如：https://form.beta.kim/?type=string&tab=2

**Comment by sscfaith** [comment]
这种需求还是自己改源码部署吧。另外avue的配置无法是纯json，因为有的value值是function，json并不支持function。要想完美的配合使用，建议你们数据库字段类型不要使用json格式，而是varchar/text。

**Comment by hhr66** [comment]
好的，谢谢您的建议，我尝试下看看行不行
