### ISSUE TITLE
如何调用生成的表单？

### ISSUE THREAD

**Issue by sunyubk** [sscfaith/avue-form-design#34]
创建好自定义表单之后保存的是一个json串，我将这个json串保存到数据库中，在我想要用这个表单的地方将这个json串查询出来，如何使用这个json渲染出表单页面

**Comment by sscfaith** [comment]
```html
<template>
  <avue-form :option="option"
             v-model="form"
             v-if="option && option.column && option.column.length > 0"></avue-form>
</template>

<script>
export default {
  data() {
    return {
      option: {},
      form: {}
    }
  },
  mounted() {
    // 模拟请求
    fetch().then(data => {
      // 假如data是保存在数据库的json串
      this.option = eval("(" + data + ")")
    })
  }
}
</script>

```

**Comment by sunyubk** [comment]
好的，谢谢，怎么用生成的json串生成表单，我已经试出来了。但是我发现一个问题，就是页面中有生成json和预览，这两个功能中都有保存/确定，那个才应该是保存json到数据库的按钮呢？生成json是@submit调用的方法。预览中的确认按钮点击只是以弹窗的方式展示了form表单的键值对。而且我没找到在哪里调用的方法。。。。。

**Comment by sscfaith** [comment]
生成json的‘生成’按钮是@submit的回调。使用不习惯的话，组件的顶部操作栏可以自定义。
```html
<template>
  <avue-form-design ref="form"
                    style="height: 100vh;"
                    :options="options"
                    :toolbar="['import', 'preview', 'clear']">
    <template slot="toolbar-left">
      <el-button type="text"
                  icon="el-icon-download"
                  @click="handleGetData">获取JSON</el-button>
    </template>
  </avue-form-design>
</template>

<script>
export default {
  data() {
    return {
      options: `{ column: [{ type: 'input', label: '输入框', prop: 'input', span: 24, display: true, event: { change: () => { console.log('111') } } }] }`
    }
  },
  methods: {
    handleGetData() {
      this.$refs.form.getData().then(data => {
        this.$message.success("查看控制台")
        console.log(data)
      })
    }
  }
}
</script>
```
具体还有什么属性，可以看READE.md里面。。。

**Comment by sunyubk** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SSC"<notifications@github.com&gt;; 
发送时间: 2020年11月2日(星期一) 下午4:10
收件人: "sscfaith/avue-form-design"<avue-form-design@noreply.github.com&gt;; 
抄送: "孙宇"<1870971964@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sscfaith/avue-form-design] 如何调用生成的表单？ (#34)





 
生成json的‘生成’按钮是@submit的回调。使用不习惯的话，组件的顶部操作栏可以自定义。
 <template&gt;   <avue-form-design ref="form"                     style="height: 100vh;"                     :options="options"                     :toolbar="['import', 'preview', 'clear']"&gt;     <template slot="toolbar-left"&gt;       <el-button type="text"                   icon="el-icon-download"                   @click="handleGetData"&gt;获取JSON</el-button&gt;     </template&gt;   </avue-form-design&gt; </template&gt; <script&gt; export default {   data() {     return {       options: `{ column: [{ type: 'input', label: '输入框', prop: 'input', span: 24, display: true, event: { change: () =&gt; { console.log('111') } } }] }`     }   },   methods: {     handleGetData() {       this.$refs.form.getData().then(data =&gt; {         this.$message.success("查看控制台")         console.log(data)       })     }   } } </script&gt;
 
具体还有什么属性，可以看READE.md里面。。。

**Comment by xiaoshuangyang** [comment]
我想问一下，我使用avue-form生成表单会提示 [Vue warn]: Missing required prop: "value"，这个报错是什么原因呢

**Comment by sunyubk** [comment]
兄弟，你问错地方了吧，我这个issue已经关闭了，你再重新创建一个issue吧😂
