### ISSUE TITLE
下拉框value的值为int，默认值填数字，会解析成字符串

### ISSUE THREAD

**Issue by hhr66** [sscfaith/avue-form-design#37]
{
  column: [
    {
      type: 'select',
      label: '名称',
      dicData: [
        {
          label: '选项一',
          value: 0
        },
        {
          label: '选项二',
          value: 1
        },
        {
          label: '选项三',
          value: 2
        }
      ],
      cascaderItem: [],
      span: 24,
      display: true,
      props: {
        label: 'label',
        value: 'value'
      },
      prop: 'name',
      value: '0'
    }
  ],
  labelPosition: 'left',
  labelSuffix: '：',
  labelWidth: 120,
  gutter: 0,
  menuBtn: true,
  submitBtn: true,
  submitText: '提交',
  emptyBtn: true,
  emptyText: '清空',
  menuPosition: 'center'
}

**Comment by sscfaith** [comment]
input框输入的都是字符串，可使用数据类型来规定字典值的类型。
![image](https://user-images.githubusercontent.com/23066241/100071168-b654e380-2e75-11eb-9c24-42b23d84dc2d.png)

**Comment by hhr66** [comment]
请问https://form.avuejs.com/的代码什么时候更新？

**Comment by sscfaith** [comment]
那个不归我管，伟总过段时间会更新一次。这个是最新的[链接](https://form.beta.kim/)

**Comment by hhr66** [comment]
npm 包最新版本是@sscfaith/avue-form-design@1.3.11  ，这个版本大概多久更新？

**Comment by hhr66** [comment]
![image](https://user-images.githubusercontent.com/7497063/100173378-5ad23680-2f05-11eb-9f1d-998f98db7ecd.png)
生成的数据还是有问题
{
  column: [
    {
      type: 'select',
      label: '下拉选择器',
      dicData: [
        {
          label: '选项一',
          value: 0
        },
        {
          label: '选项二',
          value: 1
        },
        {
          label: '选项三',
          value: 2
        }
      ],
      cascaderItem: [],
      span: 24,
      display: true,
      props: {
        label: 'label',
        value: 'value'
      },
      prop: '1606269632731_44724',
      dataType: 'number',
      value: '0'
    }
  ],
  labelPosition: 'left',
  labelSuffix: '：',
  labelWidth: 120,
  gutter: 0,
  menuBtn: true,
  submitBtn: true,
  submitText: '提交',
  emptyBtn: true,
  emptyText: '清空',
  menuPosition: 'center'
}
