### ISSUE TITLE
下拉选择器问题反馈

### ISSUE THREAD

**Issue by tonyswift123** [sscfaith/avue-form-design#45]
下拉选择框想要选中指定的默认值，无法选中

**Comment by sscfaith** [comment]
{
  column: [
    {
      type: 'select',
      label: '下拉选择器',
      dicData: [
        {
          label: '选项一',
          value: '0'
        },
        {
          label: '选项二',
          value: '1'
        },
        {
          label: '选项三',
          value: '2'
        }
      ],
      span: 24,
      display: true,
      props: {
        label: 'label',
        value: 'value'
      },
      prop: '1609721453230_97058',
      value: '1'
    }
  ]
}
