### ISSUE TITLE
为什么组件属性中没有 居中设置项

### ISSUE THREAD

**Issue by luisxin** [sscfaith/avue-form-design#48]
是会在后续版本中支持吗

**Comment by sscfaith** [comment]
什么的居中设置项？举个例子

**Comment by luisxin** [comment]
![image](https://user-images.githubusercontent.com/16147110/110417345-63273980-80d0-11eb-8ac5-969d37305ad3.png)
类似这样的标题就无法居中了

**Comment by sscfaith** [comment]
avue没这个功能，不过你可以参考[自定义组件](https://gitee.com/sscgh/avue-form-design-demo)来实现你的功能
