### ISSUE TITLE
子表单bug

### ISSUE THREAD

**Issue by newkdd** [sscfaith/avue-form-design#5]
添加子表单后，预览界面点击添加，录入子表单数值时添加和删除按钮会丢失，提供的演示界面无此问题，git下载后缺少core-js，直接安装运行后存在此问题。
![image](https://user-images.githubusercontent.com/29397778/71559577-af252a00-2a9a-11ea-98ec-7cfcd3fbb517.png)

**Comment by newkdd** [comment]
![image](https://user-images.githubusercontent.com/29397778/71559560-82711280-2a9a-11ea-8995-cab171177e63.png)

**Comment by sscfaith** [comment]
感谢，avue2.3的bug，已反馈给作者。先暂时使用avue2.2.3，等待avue修复时再升级。
