### ISSUE TITLE
整合到自己项目中报错，单独运行项目没问题麻烦看看

### ISSUE THREAD

**Issue by fanqieo** [sscfaith/avue-form-design#53]
有几个组件报错，其他正常，但是预览和获取数据都没问题
1：多选框组
![image](https://user-images.githubusercontent.com/25625919/115821243-093ac300-a435-11eb-840f-1e9eaf6fe258.png)
2: 时间
![image](https://user-images.githubusercontent.com/25625919/115821342-312a2680-a435-11eb-9f6c-7f96a0aed2ad.png)
3:时间范围
![image](https://user-images.githubusercontent.com/25625919/115821390-4a32d780-a435-11eb-9416-6b8778a6e031.png)
暂时就中3个组件拖拉到位置后会报错，但是预览貌似都正常能正常获取到数据
![image](https://user-images.githubusercontent.com/25625919/115821558-99790800-a435-11eb-94df-1cffe361056b.png)
我单独弄个空的VUE项目，整合这个插件也是报错，看来不是自己项目环境问题

**Comment by sscfaith** [comment]
![image](https://user-images.githubusercontent.com/23066241/115845119-1c5c8b80-a453-11eb-9ee9-7fdc7ec04d6c.png)
WidgetFormItem.vue 添加这个 
```html
:value="['time', 'timerange', 'checkbox'].includes(item.type) ? item.dicData: undefined"
```

**Comment by sscfaith** [comment]
你是npm安装的吗？稍等 我发个新版本

**Comment by fanqieo** [comment]
是的，npm安装的，感觉大佬

**Comment by sscfaith** [comment]
新版本1.4.3已发布

**Comment by fanqieo** [comment]
可以了谢谢大佬，麻烦问下不是NPM安装的话还有那些方式啊。可以直接把源码打包吗？还是咋弄？能指点下吗？

**Comment by sscfaith** [comment]
三种方式
1. 直接把源码拷贝到你的项目，main.js use
2. yarn lib命令可以打包成js，在index.html引入js，main.js use
3. npm安装
