### ISSUE TITLE
整合到自己项目当中后，富文本不能绑定值，也没有任何报错。

### ISSUE THREAD

**Issue by liangyuezhong** [sscfaith/avue-form-design#56]
![image](https://user-images.githubusercontent.com/78687146/120579940-e69bc100-c45a-11eb-837a-f525d108b7d2.png)

**Comment by sscfaith** [comment]
可以试下升级 avue-plugin-ueditor 至 0.2.2版本

**Comment by liangyuezhong** [comment]
谢谢大佬，雀巢咖啡已买
