### ISSUE TITLE
自定义组件title 没法修改，还有自定义组件没法分类

### ISSUE THREAD

**Issue by momosv** [sscfaith/avue-form-design#57]
![image](https://user-images.githubusercontent.com/33799449/120741773-3dbb9780-c528-11eb-8851-061daf956e55.png)

**Comment by momosv** [comment]
“自定义字段”这几个字建议支持修改，
甚至支持多分类自定义字段配置，目前只有一栏
[
  {
    title: 'title2',
    list: []
    }，
  {
    title: 'title2',
    list: []
    }，
    ]

**Comment by sscfaith** [comment]
[最新版](https://github.com/sscfaith/avue-form-design/blob/master/CHANGELOG.md)已支持

**Comment by Tom20020102** [comment]
@momosv 请问您的自定义字段是怎么配置的呢，是select来的吗？
