### ISSUE TITLE
你好，我自定义一个控件没问题了，但是如何获取到这个值呢?

### ISSUE THREAD

**Issue by fanqieo** [sscfaith/avue-form-design#60]
![image](https://user-images.githubusercontent.com/25625919/131980842-151434a7-61ea-4e72-a88d-b657621f7655.png)
![image](https://user-images.githubusercontent.com/25625919/131980871-5bdb3420-0e21-41a2-a59a-48385081d535.png)
但是点击确认获取到值为空，要如何设定属性?
![image](https://user-images.githubusercontent.com/25625919/131981025-917a851b-5d57-4909-90fa-824a375e3c50.png)

**Comment by sscfaith** [comment]
props里面value属性接收值，组件值改变时this.$emit(“input”, value) 返回值。v-model功能。
