### ISSUE TITLE
关于新增自定义组件

### ISSUE THREAD

**Issue by Yerik007** [sscfaith/avue-form-design#81]
这是否是封装完整无法修改的，追寻到WidgetFormTable.vue，handleWidgetTableAdd（）方法之后，我不知道改怎么写了，求大佬指教一下，感激不尽。
我直接在上面判断写了组件，进行拖拽的时候就消失了，

**Comment by sscfaith** [comment]
[wiki](https://github.com/sscfaith/avue-form-design/wiki) <br>

**Comment by Yerik007** [comment]
不好意思，我眼瞎，蟹蟹蟹蟹，谢谢您
